const actionTypes = {
    FAILURE: 'FAILURE',
    RESET: 'RESET',
    LOAD_DATA: 'LOAD_DATA',
    UPDATE_DATA: 'UPDATE_DATA',
    LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
    LOAD_POST: 'LOAD_POST',
    LOAD_POST_SUCCESS: 'LOAD_POST_SUCCESS',
    UPVOTE: 'UPVOTE',
    DOWNVOTE: 'DOWNVOTE',
    SORT: 'SORT',
    UPDATE_PAGINATION : 'UPDATE_PAGINATION',
    LOAD_MORE : 'LOAD_MORE',
    LOAD_MORE_SUCCESS: 'LOAD_MORE_SUCCESS',
    LOADING: 'LOADING'
  };

  export {
    actionTypes
  };